app:
  name: diengid-backend
  prefork: false

web:
  port: 8088

log:
  level: 8

database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  name: "db_diengsid"
  sslmode: "disable"
  timezone: "Asia/Jakarta"
  pool:
    idle: 10
    max: 100
    lifetime: 300

mail:
  host: smtp.gmail.com
  port: 587
  username: iddiengs@gmail.com
  password: "lkpe qqmx degv biip"

googe:
  clientId: 314501383101-t83bulhqb5ugib4s57t5hepheqt2rdgo.apps.googleusercontent.com
